import java.security.InvalidParameterException;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class Calculator {
    private double ans;

    public String getGreeting() {
        return "Custom calculator started";
    }

    public void compute(Operation operation) {
        if (operation == null) {
            throw new InvalidParameterException("Cannot perform operation");
        }
        this.ans = operation.compute();
    }

    public double getAns() {
        return ans;
    }

    public interface Operation {
        double compute();
    }

    public class Add implements Operation {
        private double left;
        private double right;
        private double result;

        public Add(double left, double right) {
            this.left = left;
            this.right = right;
        }

        public double compute() {
            this.result = left + right;
            return this.result;
        }

        public double getResult() {
            return result;
        }
    }

    public class Subtract implements Operation {
        private double left;
        private double right;
        private double result;

        public Subtract(double left, double right) {
            this.left = left;
            this.right = right;
        }

        public double compute() {
            this.result = left - right;
            return this.result;
        }

        public double getResult() {
            return result;
        }
    }

    public static void main(String[] args) {
        Calculator app = new Calculator();
        System.out.println(app.getGreeting());
        /*
        Scanner input = new Scanner(System.in);
        String line = "";
        while(app != null){
            line = input.nextLine();
            if(line == "") {
                app = null;
                break;
            }
            String[] arguments = line.split("[+-]");
            double left = Double.parseDouble(arguments[0]);
            double right = Double.parseDouble(arguments[2]);
            if(arguments[])
            System.out.println(app.getAns());
        }
        input.close();
        */
    }
}
