/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import org.junit.jupiter.api.Test;

public class AppTest {
    @Test public void appHasAGreeting() {
        Calculator classUnderTest = new Calculator();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
    @Test public void shouldAdd() {
        Calculator classUnderTest = new Calculator();
        Calculator.Add add = classUnderTest.new Add(3, 4);
        classUnderTest.compute(add);
        assertEquals(7, add.getResult());
    }
    @Test public void shouldSub() {
        Calculator classUnderTest = new Calculator();
        Calculator.Subtract sub =
            classUnderTest.new Subtract(3, 4);
        classUnderTest.compute(sub);
        assertEquals(-1, sub.getResult());
    }
    @Test public void shouldUpdateAns() {
        Calculator classUnderTest = new Calculator();
        Calculator.Subtract sub =
            classUnderTest.new Subtract(3, 4);
        classUnderTest.compute(sub);
        assertEquals(-1, classUnderTest.getAns());
    }
}
